### ISSUE TITLE
Add Copy & Paste for files and directories

### ISSUE THREAD

**Issue by greatvovan** [jupyterlab/jupyterlab-github#101]
In version 2.1.2 I can't find "Copy" item in the context menu of the _Files Browser_ as it is shown in the [documentation](https://jupyterlab.readthedocs.io/en/stable/user/files.html) on the [picture](https://jupyterlab.readthedocs.io/en/stable/_images/shareable_link.png). "Cut" item is available though.

Is it possible that my installation is somehow misconfigured or it is a bug?

My config:

```
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.port = 8888
c.NotebookApp.notebook_dir = '/app/home'
c.NotebookApp.password = 'sha1:salt:hash'
c.NotebookApp.open_browser = False
c.NotebookApp.allow_password_change = False
c.NotebookApp.allow_root = True
```

The app is launched as `jupyter lab`.

**Comment by greatvovan** [comment]
Also "Cut" and "Paste~ are in different places while they are expected to go together:

![image](https://user-images.githubusercontent.com/4903007/81214804-3a548600-8f8d-11ea-9100-72d806a33992.png)

**Comment by telamonian** [comment]
> Also "Cut" and "Paste" are in different places while they are expected to go together

Haha, yeah, that bugs me too. Unfortunately it's a baked-in artifact caused by the way that context menus are implemented in Lumino (the GUI framework that JupyterLab itself is built on). I actually fixed it a couple of years ago, but it involved some DOM hackery that I guess someone reverted in a later PR.

Are you having a problem with the github browser supplied by the jupyterlab-github plugin, or are you having an issue with the main filebrowser (which is what's shown in the documentation that you linked in your first post)?

**Comment by greatvovan** [comment]
Darn, I posted it in the wrong project. This if for main File Browser. Thanks for pointing to that. I will close the issue and post it to https://github.com/jupyterlab/jupyterlab/issues

**Comment by greatvovan** [comment]
Created here: https://github.com/jupyterlab/jupyterlab/issues/8379
