### ISSUE TITLE
GitLab support?

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-github#43]
Hi,
great plugin - thanks!

We would like to have a tab in our jupyterhub/jupyterlab setup, which directs users to example notebooks prepared especially for our clusters.

Therefore I would like to use your plugin with our own gitlab server.
How difficult do you think would it be to make this possible?

Best,
Jens

**Comment by ian-r-rose** [comment]
Hi @jhgoebbert, this plugin is fairly customized to the GitHub API, so it would not be trivial to do. That said, it does look like GitLab provides a reasonably similar API, so it *should* be possible to port the extension. Porting would involve:
1. Constructing different URLs to hit the different GitLab REST endpoints.
 2. The GitHub API returns its own JSON contents models, which we must convert to the kind of contents model that JupyterLab expects. We would also need to do that for the GitLab contents.
3. We would need to swap out the branding images.
4. There will likely be the need to change how we respond to error messages, branding information, etc.

At some point, both GitHub and GitLab will move to a GraphQL-based API, and that will likely make porting it easier.

**Comment by jhgoebbert** [comment]
Thanks for your detailed answer, Ian.
GraphQL probably would solve some issues.

Just for other readers:
GraphQL is currently planned for GitLab for 2018-Q2
* https://about.gitlab.com/okrs/
* https://gitlab.com/gitlab-org/gitlab-ce/issues/34754

**Comment by ian-r-rose** [comment]
I came across [this](https://gitlab.com/ENKI-portal/jupyterlab_gitlab) the other day, which appears to be based on this extension. I don't know how functional it is, but it may be worth investigating.

**Comment by beenje** [comment]
For those interested I created a [jupyterlab-gitlab](https://gitlab.com/beenje/jupyterlab-gitlab) extension based on  jupyterlab-github 0.10.0.

I looked at the [jupyterlab_gitlab](https://gitlab.com/ENKI-portal/jupyterlab_gitlab) extension mentioned above but it's based on a much older version of the github extension and it didn't fit my needs:
- the user can only be changed in the advanced settings
- files without a “.” in the name can’t be opened
- no server extension

That's why I decided to create a new one based on a recent version of jupyterlab-github.
This is to use at work with our own instance of GitLab.
It might be useful to others.

Thanks to the Jupyter team for the initial extension!

**Comment by ian-r-rose** [comment]
Awesome, thanks for sharing @beenje!

**Comment by beenje** [comment]
Today, the server extension is not mandatory and all the logic is in the lab extension.
The server is just used as a proxy.
But I guess the logic could be moved to the server extension...

**Comment by jtpio** [comment]
Closing as there is now a `jupyterlab-gitlab` extension under the `jupyterlab-contrib` GitHub organization: https://github.com/jupyterlab-contrib/jupyterlab-gitlab
