### ISSUE TITLE
Set default github repository on start

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-github#45]
Hello,

we would like to use your jupyterlab-github extension in a multiuser jupyterhub installation on our cluster, which shows users example notebooks (same purpose as explained in https://github.com/jupyterlab/jupyterlab-github/issues/43).

Is it possible to set a default github repository at installation time for all users
which is linked to the Home-button instead of an <EDIT USER>?

Best,
Jens Henrik

**Comment by ian-r-rose** [comment]
Hi @jhgoebbert, it should be possible to do this using the new (still experimental) workspaces feature in JupyterLab, which is still under-documented.

Briefly, you would manually go to a particular set of notebooks on GitHub, and configure the main work area in the way you want. Then, navigate the URL to `/lab/workspaces/yourworkspacenamehere`. This will cache the configuration to `~/.jupyter/lab/workspaces` on your filesystem. That workspace file can be used to seed a new instance of a JupyterHub user.

**Comment by jhgoebbert** [comment]
Hi Ian,

perfekt ... generating the workspace-file works great!
Now, how would I have to start jupyterlab to have this workspace-file (moved to a global position on the system) been used?

Can it be added as an argument to the "jupyter lab ..." command?

Best,
Jens Henrik

**Comment by ian-r-rose** [comment]
I have not experimented with the much myself, but I believe that you can place the workspace file in the users `~/.jupyter/lab/workspaces` upon image creation time, and then send them to the same workspaces URL as above when they launch lab. That is, their default URL would be `lab/workspaces/yourworkspacename`.

**Comment by dhirschfeld** [comment]
For myself, I'd just like to be able to configure a `default_user` so that when a user first opens the GitHub Tab they're greeted with a listing of the LearnPython organisation:

![image](https://user-images.githubusercontent.com/881019/38990313-1b2bf51e-441d-11e8-971a-e10ade7d1485.png)


...rather than the blank `<Edit User>` template:

![image](https://user-images.githubusercontent.com/881019/38990405-7dcb2e24-441d-11e8-84f1-7c3347626012.png)

Would that be possible without using workspaces which seems a bit of a heavyweight solution to the problem.
